/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicaGrupal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Scanner;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author alemg
 */
public class InterfazMain extends javax.swing.JFrame {

    /**
     * Creates new form InterfazMain
     */
    public InterfazMain() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        panel.setOpaque(false);
        Imagen2 im = new Imagen2(panel);
        panel.add(im).repaint();
        
        Icon icono = new ImageIcon(getClass().getResource("/imagenes/boton-personaje.png"));
        botonPersonaje.setIcon(icono);
        Icon icono1 = new ImageIcon(getClass().getResource("/imagenes/boton-recurso.png"));
        botonRecurso.setIcon(icono1);
        Icon icono2 = new ImageIcon(getClass().getResource("/imagenes/boton-combate.png"));
        botonCombate.setIcon(icono2);
        Icon icono3 = new ImageIcon(getClass().getResource("/imagenes/boton-historial.png"));
        botonHistorial.setIcon(icono3);
        Icon icono4 = new ImageIcon(getClass().getResource("/imagenes/boton-cargar.png"));
        cargar.setIcon(icono4);
        Icon icono5 = new ImageIcon(getClass().getResource("/imagenes/boton-guardar.png"));
        guardar.setIcon(icono5);
        Icon icono6 = new ImageIcon(getClass().getResource("/imagenes/boton-salir.png"));
        salir.setIcon(icono6);
        
        Image iconoP = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/icono-informalia.png")); 
        this.setIconImage(iconoP);
    }
    private static RegistroJuego registro = new RegistroJuego();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        cargar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        botonPersonaje = new javax.swing.JButton();
        botonRecurso = new javax.swing.JButton();
        botonCombate = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informalia");

        cargar.setBorderPainted(false);
        cargar.setContentAreaFilled(false);
        cargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cargarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cargarMouseExited(evt);
            }
        });
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        guardar.setBorderPainted(false);
        guardar.setContentAreaFilled(false);
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                guardarMouseExited(evt);
            }
        });
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        botonPersonaje.setBorderPainted(false);
        botonPersonaje.setContentAreaFilled(false);
        botonPersonaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonPersonajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonPersonajeMouseExited(evt);
            }
        });
        botonPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonajeActionPerformed(evt);
            }
        });

        botonRecurso.setBorderPainted(false);
        botonRecurso.setContentAreaFilled(false);
        botonRecurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRecursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRecursoMouseExited(evt);
            }
        });
        botonRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecursoActionPerformed(evt);
            }
        });

        botonCombate.setBorderPainted(false);
        botonCombate.setContentAreaFilled(false);
        botonCombate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCombateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCombateMouseExited(evt);
            }
        });
        botonCombate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCombateActionPerformed(evt);
            }
        });

        botonHistorial.setBorderPainted(false);
        botonHistorial.setContentAreaFilled(false);
        botonHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonHistorialMouseExited(evt);
            }
        });
        botonHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHistorialActionPerformed(evt);
            }
        });

        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(botonPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(botonCombate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        registro.getListaPersonajes().clear();
        registro.getListaRecursos().clear();
        registro.getListaCombate().clear();
        registro.CargarFichero();
    }//GEN-LAST:event_cargarActionPerformed
        
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        JFileChooser fc = new JFileChooser();
        File directorio = new File (fc.getCurrentDirectory(), "Informalia"); //CREA UNA CARPETA INFORMALIA EN LA CARPETA DOCUMENTOS DEL PC
        directorio.mkdir();
        File f = new File(directorio, "informalia.dat");
        try {
            if(f.exists()) {
                InterfazGuardar ig = new InterfazGuardar(this, true);
                ig.setVisible(true);
            }
            else {
                FileOutputStream fos = new FileOutputStream(f);
                ObjectOutputStream escribir = new ObjectOutputStream(fos);
                int i = 0;
                while(i<registro.getListaPersonajes().size()) {
                    escribir.writeObject(registro.getListaPersonajes().get(i));
                    i++;
                }
                i = 0;
                while(i<registro.getListaRecursos().size()) {
                    escribir.writeObject(registro.getListaRecursos().get(i));
                    i++;
                }
                i = 0;
                while(i<registro.getListaCombate().size()) {
                    escribir.writeObject(registro.getListaCombate().get(i));
                    i++;
                }
                fos.close();
                escribir.close();
            }
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void botonCombateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCombateActionPerformed
        InterfazInicioCombate c = new InterfazInicioCombate(this, true);
        c.setVisible(true);
    }//GEN-LAST:event_botonCombateActionPerformed

    private void botonPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonajeActionPerformed
        InterfazPersonaje p = new InterfazPersonaje(this, true);
        p.setVisible(true);
    }//GEN-LAST:event_botonPersonajeActionPerformed

    private void botonRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecursoActionPerformed
        InterfazRecurso r = new InterfazRecurso(this, true);
        r.setVisible(true);
    }//GEN-LAST:event_botonRecursoActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        InterfazHistorial h = new InterfazHistorial(this, true);
        h.setVisible(true);
    }//GEN-LAST:event_botonHistorialActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
	System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void botonPersonajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPersonajeMouseEntered
        Icon icono = new ImageIcon(getClass().getResource("/imagenes/boton-personaje2.png"));
        botonPersonaje.setIcon(icono);
    }//GEN-LAST:event_botonPersonajeMouseEntered

    private void botonPersonajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPersonajeMouseExited
        Icon icono = new ImageIcon(getClass().getResource("/imagenes/boton-personaje.png"));
        botonPersonaje.setIcon(icono);
    }//GEN-LAST:event_botonPersonajeMouseExited

    private void botonRecursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRecursoMouseEntered
        Icon icono1 = new ImageIcon(getClass().getResource("/imagenes/boton-recurso2.png"));
        botonRecurso.setIcon(icono1);
    }//GEN-LAST:event_botonRecursoMouseEntered

    private void botonRecursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRecursoMouseExited
        Icon icono1 = new ImageIcon(getClass().getResource("/imagenes/boton-recurso.png"));
        botonRecurso.setIcon(icono1);
    }//GEN-LAST:event_botonRecursoMouseExited

    private void botonCombateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCombateMouseEntered
        Icon icono2 = new ImageIcon(getClass().getResource("/imagenes/boton-combate2.png"));
        botonCombate.setIcon(icono2);
    }//GEN-LAST:event_botonCombateMouseEntered

    private void botonCombateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCombateMouseExited
        Icon icono2 = new ImageIcon(getClass().getResource("/imagenes/boton-combate.png"));
        botonCombate.setIcon(icono2);
    }//GEN-LAST:event_botonCombateMouseExited

    private void botonHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHistorialMouseEntered
        Icon icono3 = new ImageIcon(getClass().getResource("/imagenes/boton-historial2.png"));
        botonHistorial.setIcon(icono3);
    }//GEN-LAST:event_botonHistorialMouseEntered

    private void botonHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHistorialMouseExited
        Icon icono3 = new ImageIcon(getClass().getResource("/imagenes/boton-historial.png"));
        botonHistorial.setIcon(icono3);
    }//GEN-LAST:event_botonHistorialMouseExited

    private void cargarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarMouseEntered
        Icon icono4 = new ImageIcon(getClass().getResource("/imagenes/boton-cargar2.png"));
        cargar.setIcon(icono4);
    }//GEN-LAST:event_cargarMouseEntered

    private void cargarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarMouseExited
        Icon icono4 = new ImageIcon(getClass().getResource("/imagenes/boton-cargar.png"));
        cargar.setIcon(icono4);
    }//GEN-LAST:event_cargarMouseExited

    private void guardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseEntered
        Icon icono5 = new ImageIcon(getClass().getResource("/imagenes/boton-guardar2.png"));
        guardar.setIcon(icono5);
    }//GEN-LAST:event_guardarMouseEntered

    private void guardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseExited
        Icon icono5 = new ImageIcon(getClass().getResource("/imagenes/boton-guardar.png"));
        guardar.setIcon(icono5);
    }//GEN-LAST:event_guardarMouseExited

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        Icon icono6 = new ImageIcon(getClass().getResource("/imagenes/boton-salir2.png"));
        salir.setIcon(icono6);
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        Icon icono6 = new ImageIcon(getClass().getResource("/imagenes/boton-salir.png"));
        salir.setIcon(icono6);
    }//GEN-LAST:event_salirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMain().setVisible(true);
            }
        });
    }
    
    public RegistroJuego getRegistroJuego() {
        return registro;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCombate;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonPersonaje;
    private javax.swing.JButton botonRecurso;
    private javax.swing.JButton cargar;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel panel;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
