/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package practicaGrupal;

/**
 *
 * @author David_2
 */
public class InterfazRecurso extends javax.swing.JDialog {

    /**
     * Creates new form InterfazRecurso
     */
    public InterfazRecurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        panelarma.setVisible(false);
        
        for (Recurso rec: registro2.getListaRecursos()){
            
            RecursosCreados1.addItem(rec.getNombre() + " " + rec.getID());
            RecursosCreados2.addItem(rec.getNombre() + " " + rec.getID());
        }
    }
    InterfazMain i = new InterfazMain();
    RegistroJuego registro2 = i.getRegistroJuego();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elegirManejo = new javax.swing.ButtonGroup();
        elegirRango = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        CrearRecurso = new javax.swing.JButton();
        TipoRecurso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        NombreTexto = new javax.swing.JTextField();
        panelarma = new javax.swing.JPanel();
        UnaMano = new javax.swing.JRadioButton();
        DosManos = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        distancia = new javax.swing.JRadioButton();
        cuerpo = new javax.swing.JRadioButton();
        ModificarRecurso = new javax.swing.JButton();
        RecursosCreados1 = new javax.swing.JComboBox<>();
        NuevoNombreTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EliminarBoton = new javax.swing.JButton();
        RecursosCreados2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        Volver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recurso");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearRecurso.setText("Crear");
        CrearRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearRecursoActionPerformed(evt);
            }
        });
        jPanel1.add(CrearRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 167, 90, -1));

        TipoRecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arma", "Hechizo", "Conjuro" }));
        TipoRecurso.setSelectedIndex(-1);
        TipoRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoRecursoActionPerformed(evt);
            }
        });
        jPanel1.add(TipoRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 168, 85, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 171, -1, -1));

        NombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextoActionPerformed(evt);
            }
        });
        jPanel1.add(NombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 168, 103, -1));

        panelarma.setOpaque(false);

        elegirManejo.add(UnaMano);
        UnaMano.setForeground(new java.awt.Color(255, 255, 255));
        UnaMano.setText("Una mano");

        elegirManejo.add(DosManos);
        DosManos.setForeground(new java.awt.Color(255, 255, 255));
        DosManos.setText("Dos manos");
        DosManos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DosManosActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manejo:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rango:");

        elegirRango.add(distancia);
        distancia.setForeground(new java.awt.Color(255, 255, 255));
        distancia.setText("A distancia");
        distancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanciaActionPerformed(evt);
            }
        });

        elegirRango.add(cuerpo);
        cuerpo.setForeground(new java.awt.Color(255, 255, 255));
        cuerpo.setText("Cuerpo a cuerpo");

        javax.swing.GroupLayout panelarmaLayout = new javax.swing.GroupLayout(panelarma);
        panelarma.setLayout(panelarmaLayout);
        panelarmaLayout.setHorizontalGroup(
            panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelarmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(DosManos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnaMano, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuerpo))
                .addGap(40, 40, 40))
        );
        panelarmaLayout.setVerticalGroup(
            panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelarmaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnaMano)
                    .addComponent(distancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelarmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DosManos)
                    .addComponent(cuerpo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(panelarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 132, -1, -1));

        ModificarRecurso.setText("Modificar");
        ModificarRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarRecursoActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarRecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, -1));

        RecursosCreados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecursosCreados1MouseClicked(evt);
            }
        });
        RecursosCreados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecursosCreados1ActionPerformed(evt);
            }
        });
        jPanel1.add(RecursosCreados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 85, -1));

        NuevoNombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoNombreTextoActionPerformed(evt);
            }
        });
        jPanel1.add(NuevoNombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 103, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, 20));

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 349, 90, -1));

        jPanel1.add(RecursosCreados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 349, 85, -1));

        area.setEditable(false);
        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 426, 750, -1));

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-volver.png"))); // NOI18N
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 65, 48));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/titulo-recursos.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-recursos.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearRecursoActionPerformed
        if((NombreTexto.getText().trim().equals(""))||(TipoRecurso.getSelectedIndex()==-1)) {
            area.setText("Error al crear recurso. Hay algún campo vacío");
        }
        else {
            Recurso rec=null;
            switch(TipoRecurso.getSelectedIndex()) {
                case 0: {
                    int manejo=0;
                    int rango=0;
                    if(UnaMano.isSelected()){manejo=1;}
                    else if(DosManos.isSelected()){manejo=2;}
                    if(cuerpo.isSelected()){rango=0;}
                    else if(distancia.isSelected()){rango=(int)(Math.random()*9+1);}
                    rec = new Arma(NombreTexto.getText(),registro2,rango,manejo); 
                } break;
                case 1: {
                    rec = new Hechizo( NombreTexto.getText(),registro2);
                } break;
                case 2: {
                    rec = new Conjuro(NombreTexto.getText(),registro2);
                } break;
            }
            RecursosCreados1.addItem(rec.getNombre() + " " + rec.getID());
            RecursosCreados2.addItem(rec.getNombre() + " " + rec.getID());
            area.setText("Recurso creado con éxito" + "\n" + rec.toString());
            NombreTexto.setText("");
            panelarma.setVisible(false);
            elegirManejo.clearSelection();
            elegirRango.clearSelection();

            try {
                TipoRecurso.setSelectedIndex(-1);
            } catch(java.lang.NullPointerException e) {

            }
        }
    }//GEN-LAST:event_CrearRecursoActionPerformed

    private void NombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTextoActionPerformed

    private void NuevoNombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoNombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoNombreTextoActionPerformed

    private void ModificarRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarRecursoActionPerformed
        if((NuevoNombreTexto.getText().trim().equals(""))||(RecursosCreados1.getSelectedIndex()==-1)) {
            area.setText("Error al modificar recurso. Hay algún campo vacío");
        }
        else {
            Recurso rec = registro2.getListaRecursos().get(RecursosCreados1.getSelectedIndex());
            rec.setNombre(NuevoNombreTexto.getText());
            RecursosCreados1.removeAllItems();
            RecursosCreados2.removeAllItems();
            for (Recurso rec2: registro2.getListaRecursos()){
                RecursosCreados1.addItem(rec2.getNombre() + " " + rec2.getID());
                RecursosCreados2.addItem(rec2.getNombre() + " " + rec2.getID());
            }
            area.setText("Recurso modificado con éxito" + "\n" + rec.toString());
            NuevoNombreTexto.setText("");
        }
    }//GEN-LAST:event_ModificarRecursoActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        if(RecursosCreados2.getSelectedIndex()==-1) {
            area.setText("Error al eliminar recurso. Hay algún campo vacío");
        }
        else {
            Recurso rec = registro2.getListaRecursos().get(RecursosCreados2.getSelectedIndex());
            if (!(rec.getEnUso())){
                registro2.EliminarRecurso(rec);
                RecursosCreados1.removeAllItems();
                RecursosCreados2.removeAllItems();
                for (Recurso rec2: registro2.getListaRecursos()){
                    RecursosCreados1.addItem(rec2.getNombre() + " " + rec2.getID());
                    RecursosCreados2.addItem(rec2.getNombre() + " " + rec2.getID());
                }
                area.setText("Recurso eliminado con éxito");
            } else{
                area.setText("El recurso está en uso por un personaje, devuélvalo antes");
            }
        }
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void RecursosCreados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecursosCreados1ActionPerformed
        
    }//GEN-LAST:event_RecursosCreados1ActionPerformed

    private void RecursosCreados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecursosCreados1MouseClicked

    }//GEN-LAST:event_RecursosCreados1MouseClicked

    private void DosManosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DosManosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DosManosActionPerformed

    private void TipoRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoRecursoActionPerformed
        if(TipoRecurso.getSelectedItem().equals("Arma")){
            panelarma.setVisible(true);
            UnaMano.setVisible(true);
            DosManos.setVisible(true);
            
        }else{
            panelarma.setVisible(false);
        }
    }//GEN-LAST:event_TipoRecursoActionPerformed

    private void distanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distanciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazRecurso dialog = new InterfazRecurso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearRecurso;
    private javax.swing.JRadioButton DosManos;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JButton ModificarRecurso;
    private javax.swing.JTextField NombreTexto;
    private javax.swing.JTextField NuevoNombreTexto;
    private javax.swing.JComboBox<String> RecursosCreados1;
    private javax.swing.JComboBox<String> RecursosCreados2;
    private javax.swing.JComboBox<String> TipoRecurso;
    private javax.swing.JRadioButton UnaMano;
    private javax.swing.JButton Volver;
    private javax.swing.JTextArea area;
    private javax.swing.JRadioButton cuerpo;
    private javax.swing.JRadioButton distancia;
    private javax.swing.ButtonGroup elegirManejo;
    private javax.swing.ButtonGroup elegirRango;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelarma;
    // End of variables declaration//GEN-END:variables
}
